Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManager.Mvc.Models
{
    public class AppDbContext:DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) :base(options)
        {
        }
        public DbSet<Employee> Employees { get; set; }

        public DbSet<Country> Countries { get; set; }

    }
}

Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManager.Mvc.Models
{
    public class Country
    {
        public int CountryID { get; set; }
        public string Name { get; set; }
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EmployeeManager.Mvc.Models
{
    //Represents the Employee Database inside Northwind
    [Table(name:"Employees")]
    public class Employee
    {
        [Column(name:"EmployeeID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required(ErrorMessage = "Employee ID is required")]
        [Display(Name ="Employee ID")]
        public int EmployeeID { get; set; }

        [Column(name: "FirstName")]
        [Required(ErrorMessage = "First Name is required")]
        [Display(Name = "First Name")]
        [StringLength(10,ErrorMessage = "First Name must be less than 10 characters")]
        public string FirstName { get; set; }

        [Column(name: "LastName")]
        [Required(ErrorMessage = "Last Name is required")]
        [Display(Name = "Last Name")]
        [StringLength(20, ErrorMessage = "Last Name must be less than 20 characters")]
        public string LastName { get; set; }

        [Column(name: "Title")]
        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Title")]
        [StringLength(30, ErrorMessage = "Title must be less than 30 characters")]
        public string Title { get; set; }

        [Column(name: "BirthDate")]
        [Required(ErrorMessage = "BirthDate is required")]
        [Display(Name = "Birth Date")]
        
        public DateTime BirthDate { get; set; }

        [Column(name: "HireDate")]
        [Required(ErrorMessage = "Hire Date is required")]
        [Display(Name = "Hire Date")]
        public DateTime HireDate { get; set; }

        [Column(name: "Country")]
        [Required(ErrorMessage = "Country is required")]
        [Display(Name = "Country")]
        [StringLength(15, ErrorMessage = "Country must be less than 15 characters")]
        public string Country { get; set; }

        [Column(name: "Notes")]
        [Display(Name = "Notes")]
        [StringLength(500, ErrorMessage = "Notes must be less than 500 characters")]
        public string Notes { get; set; }


    }
}

Controllers/EmployeeManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeManager.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeManager.Mvc.Controllers
{
    public class EmployeeManagerController : Controller
    {
        private AppDbContext db = null;
        public EmployeeManagerController(AppDbContext db)
        {
            this.db = db;
        }

        public IActionResult List()
        {
            List<Employee> model =
                (from e in this.db.Employees
                 orderby e.EmployeeID
                 select e).ToList();
            return View(model);
        }

        private void FillCountries()
        {
            var countries =
                (from c in db.Countries
                 orderby c.Name ascending
                 select new SelectListItem()
                 {
                     Text = c.Name,
                     Value = c.CountryID.ToString()
                 }
                 ).ToList();
            ViewBag.Countries = countries;
        }

        
    }
}

Views/EmployeeManager/List.cshtml
@{
    @model List<Employee>
}
<h2>List of Employees</h2>
<h2 class="message">@TempData</h2>
<a asp-controller="Employeemanager"
   asp-action="Insert"
   class="linkbutton">Insert</a>
<br />
<br />

<table border="1">
    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Title</th>
        <th colspan="2">Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.EmployeeID</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Title</td>

            <td><a asp-controller="EmployeeManager"
                   asp-action="Update"
                   asp-route-id="@item.EmployeeID"
                   class="linkbutton">Update</a>
            </td>

            <td>
                <a asp-controller="EmployeeManager"
                   asp-action="Delete"
                   asp-route-id="@item.EmployeeID"
                   class="linkbutton">Delete</a>
            </td>
        </tr>
    }

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery.js"></script>
    <link href="~/Styles/site.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>